//ORDENAÇÃO


//FUPQ
//LEIA UM VETOR DE TAMANHO N
// ENCONTRE O MENOR ELEMENTO DO VETOR E SUA POSIÇÃO
//TROQUE O MENOR ELEMENTO COM O 1 ELEMENTO DO VETOR
//ENCONTRE O 2MENOR ELEMENTO E COLOQUE NA 2 POSIÇÃO 
//ENCONTRE O ENÉSIMO MENOR ELEMENTO E COLOQUE NA ENÉSIMA POSIÇÃO
